### ISSUE TITLE
Possible README changes

### ISSUE THREAD

**Issue by hauten** [mfem/web#119]
I recently set up a new laptop, then cloned my fork of this repo and started following the README instructions: https://github.com/mfem/web/blob/master/README.md. Specifically these commands:

1. `pip install --upgrade --user mkdocs==1.0.4`
2. `pip install --upgrade --user Markdown==2.6.8`
3. `pip install --upgrade --user PyYAML==3.13`
4. `pip install --upgrade --user futures==3.3.0`

Questions and/or suggested changes:

- I didn't need to run the fourth command in order to get `mkdocs serve` or `mkdocs build` to work. I still haven't run it. Is `futures` necessary? If so, why?
- Both the specified `mkdocs` and `markdown` versions are old. Other repos I work on use mkdocs 1.1 and markdown 3.3.4. When switching to this one and back, I had to up/downgrade until I got tired of it and installed mkdocs 1.1 and markdown 3.3.4 here to see if they would work. The site seems to build fine locally with these newer versions (including the dynamic /examples dropdowns), so perhaps the first two commands could be updated. Or must the respective versions 1.0.4 and 2.6.8 be enforced? If so, why?

(I don't know why these issues didn't come up on my old laptop, where I had been contributing to this repo since 2019. Maybe these are my problems and not the repo's problems! If you want the README updated according to anything in this issue, I'd be happy to do it.)

**Comment by tzanio** [comment]
Thanks for reporting this @hauten. See some answers below.

> I didn't need to run the fourth command in order to get mkdocs serve or mkdocs build to work. I still haven't run it. Is futures necessary? If so, why?

I believe this brings Python 3 features in Python 2. It is possible that you were using Python 2  in your old laptop, while the new one uses Python 3, so you don't need it anymore.

> Both the specified mkdocs and markdown versions are old. Other repos I work on use mkdocs 1.1 and markdown 3.3.4. When switching to this one and back, I had to up/downgrade until I got tired of it and installed mkdocs 1.1 and markdown 3.3.4 here to see if they would work. The site seems to build fine locally with these newer versions (including the dynamic /examples dropdowns), so perhaps the first two commands could be updated. Or must the respective versions 1.0.4 and 2.6.8 be enforced? If so, why?

Given that everyone has (hopefully) switched to Python 3 and that we fixed the issues with [mkdocs-1.0](https://github.com/mfem/web/commit/e9c2f2113335e94d3e3fb9c3b4c157bf252a577e) I am inclined to just replace the above lines with

1. `pip install --upgrade --user mkdocs`
2. `pip install --upgrade --user Markdown`
3. `pip install --upgrade --user PyYAM`

which will pull the latest versions. @v-dobrev, any objections?

@hauten, I didn't check everything carefully but I noticed one small difference with the newest version in https://mfem.org/examples/ -- the dropbox titles, e.g. `Application (PDE)`, were not rendered in bold. This could be fixed simply with

```diff
diff --git a/src/examples.md b/src/examples.md
index 7b4d00e..99f093a 100644
--- a/src/examples.md
+++ b/src/examples.md
@@ -33,7 +33,7 @@ or post [questions](https://github.com/mfem/mfem/issues/new?labels=question) or
 
 <div class="row" markdown="1">
 <div class="col-sm-6 col-md-2 small" markdown="1">
-   <h5>**Application (PDE)**</h5>
+   <h5><b>Application (PDE)</b></h5>
    <select id="group1" onchange="update()">
       <option id="all1">All</option>
       <option id="diffusion">Diffusion</option>
```

Do you also see this?

**Comment by hauten** [comment]
I compared all the pages linked in the site nav on local vs prod. The bold issue @tzanio notes above is the only problem I saw with how markdown is rendering in a newer version. I will submit a PR with the changes above (using `<strong>` instead of `<b>` to let the user's CSS decide how to emphasize the dropdown headings) but will happily modify any of it if @v-dobrev disagrees or has other suggestions.

Unrelated: There are two linked cites for ref 2 on https://mfem.org/fluids/. The little back arrow appears twice at the bottom of the page next to that ref, which makes sense, but the second one doesn't do anything (doesn't take you back up to the second cite). I googled but didn't see an obvious fix.

**Comment by tzanio** [comment]
> Unrelated: There are two linked cites for ref 2 on https://mfem.org/fluids/. The little back arrow appears twice at the bottom of the page next to that ref, which makes sense, but the second one doesn't do anything (doesn't take you back up to the second cite). I googled but didn't see an obvious fix.

ping: @jandrej
