### ISSUE TITLE
Provide navigational context for tertiary+ pages

### ISSUE THREAD

**Issue by hauten** [mfem/web#134]
Pages that are not in the top-level menu (either primary or secondary dropdown) can lose a little context without navigational cues.

Example: Documentation > HowTo Articles > Parallel Element Numbering. To get back to the HowTo list (i.e., the parent of this page), I would have to know to go back to the top nav and select Documentation > HowTo Articles. I can't get back to the parent directly, and it's not active in the nav dropdown.

Breadcrumbs could be one solution. The bootstrap CSS files have a breadcrumbs style already defined. Another idea is to insert a "Back to HowTo Articles" link (or similar) on these pages, though contributors would have to remember to do that manually if it's not built in. Alternatively, I wonder if the right-side nav within a page (where the page's headings are listed) could be modified to include a link back to the parent page.

I don't have enough practice with mkdocs sites to know the correct logic. My initial attempts to modify `content.html` failed: capture breadcrumb from page title, link it to page URL, loop through a URL by its slashes to see if it has parents, add those to the breadcrumb string, etc.

(Side note: This site has many pages where the parent is Home and/or where they are only navigable from a link on another page. For instance, I got to https://mfem.org/mesh-format-v1.0/ via Documentation > Mesh Formats > MFEM's mesh formats page. For something like that, a breadcrumb to Home isn't helpful. Or I could ask, why isn't that page under Mesh Formats in the directory? Same with Documentation > Getting Started > Parallel Tutorial. But I like having things in directories and have zero insight into site analytics. Perhaps users aren't as confused as I think they might be. In any case, in the near term, I think the biggest user impact would be to focus on the non-Doxygen pages under Documentation. At minimum the HowTo pages.)

**Comment by jakubcerveny** [comment]
This is certainly true and breadcrumbs would be nice, although I don't know how to add them either. I'm sure the website has multiple UI design problems, but I think we are already stretching mkdocs beyond its limits. In the future we might have to migrate to a more advanced system. I'm wondering what projects like https://webpack.js.org/ are using for their website?
