### ISSUE TITLE
Document the difference between LinearFormIntegrator::AssembleRHSElementVect methods L2 vs H1

### ISSUE THREAD

**Issue by tzanio** [mfem/web#165]
From https://github.com/mfem/mfem/issues/2550:

> Mixing together several discretizations, i.e. H1 and L2, requires either implementation of the two versions of LinearFormIntegrator::AssembleRHSElementVect, or a single version with FaceElementTransformations. The documentation does not provide any guidance how the different versions are used in the code. The method with FaceElementTransformations is more general and can be used with H1 and L2 fields.

**Comment by v-dobrev** [comment]
I think it may be more appropriate to document this in MFEM (with doxygen) where these methods are declared in the base class. That's why the original issue was in MFEM's repo.
