### ISSUE TITLE
Update web pages for ParaView DataCollection

### ISSUE THREAD

**Issue by tzanio** [mfem/web#27]
- [ ] Mention ParaView support in src/features.md
- [ ] Update example 5 and 9 descriptions in src/examples.md to match the mfem code
- [ ] Any additional updates for the high-order support?

**Comment by tzanio** [comment]
@bslazarov, let me know if you need help with this

**Comment by tzanio** [comment]
Resolved by #43

**Comment by tzanio** [comment]
@bslazarov and @pazner is there any cool ParaView visualization of MFEM results that we want to add to the [Gallery](https://mfem.org/gallery/)?

(We usually say, "Visualization with ..." there)

**Comment by bslazarov** [comment]
I guess Will have nice NS simulation pictures. Now I have just standard
boring pictures. I will add more exciting a bit later in time once the mtop
mini-app is up and running.

Best regards, Boyan

**Comment by tzanio** [comment]
No rush. I thought I'll ask just in case

**Comment by pazner** [comment]
Here are two Taylor-Green vortex images done in ParaView, depending on which color map you like better...

![tgv copy](https://user-images.githubusercontent.com/11493037/76190334-fcf49780-6199-11ea-899f-120a5b3efeaf.png)
![tgv2 copy](https://user-images.githubusercontent.com/11493037/76190340-ffef8800-6199-11ea-97a1-64b93fd5de3e.png)

**Comment by tzanio** [comment]
Thanks Will! Does this description look OK: https://github.com/mfem/web/pull/44/commits/47f81ecba0bb9e0ee3397ceb9006eeb89ae16e64?

**Comment by pazner** [comment]
Looks great, I would maybe just add "_incompressible_ Taylor-Green vortex"

**Comment by tzanio** [comment]
Should we say also explicitly what was the order?

**Comment by pazner** [comment]
Up to you — this particular image was with just p=2.

**Comment by jandrej** [comment]
We have that simulation data in order p=11 no?

**Comment by pazner** [comment]
The data exists. It might require some effort to extract/convert it.
