### ISSUE TITLE
Documentation on DG boundary conditions is misleading (for 1D at least)

### ISSUE THREAD

**Issue by cjvogl** [mfem/web#271]
The documentation on boundary conditions reads, "In the Discontinuous Galerkin (DG) formulation the [Natural](https://github.com/mfem/web/blob/master/src/fem_bc.md#natural-boundary-conditions), [Neumann](https://github.com/mfem/web/blob/master/src/fem_bc.md#neumann-boundary-conditions), and [Robin](https://github.com/mfem/web/blob/master/src/fem_bc.md#robin-boundary-conditions) can be implemented in precisely the same manner as in the continuous case." (see https://github.com/mfem/web/blob/12882dfb42bf16fa181a0da7b9c1c92abbb57642/src/fem_bc.md?plain=1#L217)

I found this to misleading: Natural/Neumann conditions for CG are imposed by, e.g.,  adding a boundary integrator to the RHS linear form.  Doing the same for a one-dimensional DG finite element space generates a seg fault because `L2_Elements[Geometry::POINT]` is `NULL`... so the following line in `LinearForm` fails: https://github.com/mfem/mfem/blob/master/fem/linearform.cpp#L260.

**Comment by pazner** [comment]
I suppose in DG it needs to be a boundary **face** integrator rather than a boundary integrator (added with `AddBdrFaceIntegrator` rather than `AddBoundaryIntegrator`). Please see if #272 helps clarify things.

**Comment by cjvogl** [comment]
That's exactly what I found. Thanks for putting together #272 , I'll take a look now.
