### ISSUE TITLE
Mention support for SLEPc

### ISSUE THREAD

**Issue by tzanio** [mfem/web#69]
Do we want to mention the support for SLEPc at https://mfem.org/features/ and https://mfem.org/examples/ ?

**Comment by jetremblay** [comment]
I can do that. Do I push to a new branch and start a PR?

**Comment by tzanio** [comment]
> I can do that. Do I push to a new branch and start a PR?

Yes. See for example https://github.com/mfem/web/pull/29.

Let me know if you have questions or need help.

**Comment by tzanio** [comment]
Resolved by #70
