### ISSUE TITLE
document Block Solvers miniapp

### ISSUE THREAD

**Issue by tzanio** [mfem/web#90]
See e.g. the Navier miniapp documentation in src/examples.md

cc: @chakshinglee

**Comment by chakshinglee** [comment]
@tzanio Yes, I can add some description/documentation of the miniapp to src/examples.md.

**Comment by tzanio** [comment]
ping: @chakshinglee

**Comment by tzanio** [comment]
ping: @chakshinglee

**Comment by chakshinglee** [comment]
@tzanio Sorry that this took me a while. I have a quick question regarding the picture: what is `https://glvis.org/live/?stream=..` and do I need to add a figure there?

**Comment by tzanio** [comment]
It is the `mesh`+`gf` data that can be viewed with the web version of glvis

It is totally up to you if you want to add it -- a picture is fine, a live version is extra :)

Is this clear?

**Comment by tzanio** [comment]
You can also take a look at https://glvis.org/live/ and https://github.com/GLVis/web/pull/3

**Comment by chakshinglee** [comment]
Thanks for the explanation @tzanio. I will just add a figure for the miniapp. 
BTW, when I tried to push a new branch to the repo, I got the following message 
```remote: Permission to mfem/web.git denied to ...```
Maybe I do not have write privilege?

**Comment by tzanio** [comment]
try now please

**Comment by tzanio** [comment]
Addressed by #102
